# Generated by cucumber-sinatra. (2015-05-15 10:25:34 +0100)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'lib/rps_ui.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = rps

class rps_uiWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  rps_uiWorld.new
end
